# Generated by Django 3.2.12 on 2022-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('owner_id', 'name')},
        ),
    ]
