# Generated by Django 3.2.12 on 2022-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20220304_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcompanion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
