# Generated by Django 3.2.12 on 2022-03-07 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_city_tripcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcity',
            name='dest_city_order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
